# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoalieStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlayerName', models.CharField(max_length=30)),
                ('TeamName', models.CharField(max_length=30)),
                ('GamesPlayed', models.FloatField(max_length=3)),
                ('MinutesPlayed', models.FloatField(max_length=4)),
                ('ShotsonGoal', models.FloatField(max_length=3)),
                ('Saves', models.FloatField(max_length=3)),
                ('GA', models.FloatField(max_length=3)),
                ('GAA', models.FloatField(max_length=6)),
                ('SHO', models.FloatField(max_length=2)),
            ],
        ),
    ]
