# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 18:02
from __future__ import unicode_literals

from django.db import migrations
from django.db import migrations

# apps, schema_editor
from nwsl_app.models import GoalieStats


def add_data(apps, schema_editor):
    GoalieStats.objects.create(PlayerName="Michele Dalton", TeamName="CHI", GamesPlayed=12, MinutesPlayed=1080, ShotsonGoal=113, Saves=47, GA=11, GAA=0.917, SHO=5)
    GoalieStats.objects.create(PlayerName="Nicole Barnhart", TeamName="KC", GamesPlayed=17, MinutesPlayed=1530, ShotsonGoal=179, Saves=54, GA=16, GAA=0.941, SHO=8)
    GoalieStats.objects.create(PlayerName="Haley Kopmeyer", TeamName="SEA", GamesPlayed=11, MinutesPlayed=990, ShotsonGoal=107, Saves=41, GA=11, GAA=1.000, SHO=4)
    GoalieStats.objects.create(PlayerName="Caroline Stanley", TeamName="SEA", GamesPlayed=1, MinutesPlayed=90, ShotsonGoal=6, Saves=1, GA=1, GAA=1.000, SHO=0)
    GoalieStats.objects.create(PlayerName="Hope Solo", TeamName="SEA", GamesPlayed=8, MinutesPlayed=720, ShotsonGoal=56, Saves=19, GA=9, GAA=1.125, SHO=1)
    GoalieStats.objects.create(PlayerName="Bianca Hanninger", TeamName="HOU", GamesPlayed=10, MinutesPlayed=868, ShotsonGoal=132, Saves=34, GA=11, GAA=1.141, SHO=4)
    GoalieStats.objects.create(PlayerName="Michelle Belos", TeamName="POR", GamesPlayed=14, MinutesPlayed=1260, ShotsonGoal=130, Saves=45, GA=18, GAA=1.266, SHO=2)
    GoalieStats.objects.create(PlayerName="Ashlyn Harris", TeamName="WAS", GamesPlayed=9, MinutesPlayed=810, ShotsonGoal=126, Saves=47, GA=12, GAA=1.333, SHO=1)
    GoalieStats.objects.create(PlayerName="Katelyn Rowland", TeamName="KC", GamesPlayed=3, MinutesPlayed=270, ShotsonGoal=29, Saves=13, GA=4, GAA=1.333, SHO=1)
    GoalieStats.objects.create(PlayerName="Brittany Cameron", TeamName="NJ", GamesPlayed=2, MinutesPlayed=1792, ShotsonGoal=263, Saves=87, GA=27, GAA=1.356, SHO=4)
    pass



class Migration(migrations.Migration):

    dependencies = [
        ('nwsl_app', '0001_initial'),
    ]

    operations = [
    ]
